Traceback (most recent call last):
  File "/Users/farid/Abaconda3/anaconda3/lib/python3.8/site-packages/jupyter_cache/executors/utils.py", line 51, in single_nb_execution
    executenb(
  File "/Users/farid/Abaconda3/anaconda3/lib/python3.8/site-packages/nbclient/client.py", line 1112, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/Users/farid/Abaconda3/anaconda3/lib/python3.8/site-packages/nbclient/util.py", line 74, in wrapped
    return just_run(coro(*args, **kwargs))
  File "/Users/farid/Abaconda3/anaconda3/lib/python3.8/site-packages/nbclient/util.py", line 53, in just_run
    return loop.run_until_complete(coro)
  File "/Users/farid/Abaconda3/anaconda3/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "/Users/farid/Abaconda3/anaconda3/lib/python3.8/site-packages/nbclient/client.py", line 553, in async_execute
    await self.async_execute_cell(
  File "/Users/farid/Abaconda3/anaconda3/lib/python3.8/site-packages/nbclient/client.py", line 857, in async_execute_cell
    self._check_raise_for_error(cell, exec_reply)
  File "/Users/farid/Abaconda3/anaconda3/lib/python3.8/site-packages/nbclient/client.py", line 760, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
url='https://gpm1.gesdisc.eosdis.nasa.gov/opendap/GPM_L3/GPM_3IMERGDE.06/2000/06/3B-DAY-E.MS.MRG.3IMERG.20000601-S000000-E235959.V06.nc4'
url2=''

session = requests.Session()
session.auth = ('faridfarhat', 'Stand@2020@2020@')

store = xr.backends.PydapDataStore.open(url, session=session)
ds = xr.open_dataset(store)
------------------

[0;31m---------------------------------------------------------------------------[0m
[0;31mHTTPError[0m                                 Traceback (most recent call last)
File [0;32m~/Abaconda3/anaconda3/envs/geo_env/lib/python3.10/site-packages/xarray/conventions.py:523[0m, in [0;36mdecode_cf_variables[0;34m(variables, attributes, concat_characters, mask_and_scale, decode_times, decode_coords, drop_variables, use_cftime, decode_timedelta)[0m
[1;32m    522[0m [38;5;28;01mtry[39;00m:
[0;32m--> 523[0m     new_vars[k] [38;5;241m=[39m [43mdecode_cf_variable[49m[43m([49m
[1;32m    524[0m [43m        [49m[43mk[49m[43m,[49m
[1;32m    525[0m [43m        [49m[43mv[49m[43m,[49m
[1;32m    526[0m [43m        [49m[43mconcat_characters[49m[38;5;241;43m=[39;49m[43mconcat_characters[49m[43m,[49m
[1;32m    527[0m [43m        [49m[43mmask_and_scale[49m[38;5;241;43m=[39;49m[43mmask_and_scale[49m[43m,[49m
[1;32m    528[0m [43m        [49m[43mdecode_times[49m[38;5;241;43m=[39;49m[43mdecode_times[49m[43m,[49m
[1;32m    529[0m [43m        [49m[43mstack_char_dim[49m[38;5;241;43m=[39;49m[43mstack_char_dim[49m[43m,[49m
[1;32m    530[0m [43m        [49m[43muse_cftime[49m[38;5;241;43m=[39;49m[43muse_cftime[49m[43m,[49m
[1;32m    531[0m [43m        [49m[43mdecode_timedelta[49m[38;5;241;43m=[39;49m[43mdecode_timedelta[49m[43m,[49m
[1;32m    532[0m [43m    [49m[43m)[49m
[1;32m    533[0m [38;5;28;01mexcept[39;00m [38;5;167;01mException[39;00m [38;5;28;01mas[39;00m e:

File [0;32m~/Abaconda3/anaconda3/envs/geo_env/lib/python3.10/site-packages/xarray/conventions.py:369[0m, in [0;36mdecode_cf_variable[0;34m(name, var, concat_characters, mask_and_scale, decode_times, decode_endianness, stack_char_dim, use_cftime, decode_timedelta)[0m
[1;32m    368[0m [38;5;28;01mif[39;00m decode_times:
[0;32m--> 369[0m     var [38;5;241m=[39m [43mtimes[49m[38;5;241;43m.[39;49m[43mCFDatetimeCoder[49m[43m([49m[43muse_cftime[49m[38;5;241;43m=[39;49m[43muse_cftime[49m[43m)[49m[38;5;241;43m.[39;49m[43mdecode[49m[43m([49m[43mvar[49m[43m,[49m[43m [49m[43mname[49m[38;5;241;43m=[39;49m[43mname[49m[43m)[49m
[1;32m    371[0m dimensions, data, attributes, encoding [38;5;241m=[39m variables[38;5;241m.[39munpack_for_decoding(var)

File [0;32m~/Abaconda3/anaconda3/envs/geo_env/lib/python3.10/site-packages/xarray/coding/times.py:688[0m, in [0;36mCFDatetimeCoder.decode[0;34m(self, variable, name)[0m
[1;32m    687[0m calendar [38;5;241m=[39m pop_to(attrs, encoding, [38;5;124m"[39m[38;5;124mcalendar[39m[38;5;124m"[39m)
[0;32m--> 688[0m dtype [38;5;241m=[39m [43m_decode_cf_datetime_dtype[49m[43m([49m[43mdata[49m[43m,[49m[43m [49m[43munits[49m[43m,[49m[43m [49m[43mcalendar[49m[43m,[49m[43m [49m[38;5;28;43mself[39;49m[38;5;241;43m.[39;49m[43muse_cftime[49m[43m)[49m
[1;32m    689[0m transform [38;5;241m=[39m partial(
[1;32m    690[0m     decode_cf_datetime,
[1;32m    691[0m     units[38;5;241m=[39munits,
[1;32m    692[0m     calendar[38;5;241m=[39mcalendar,
[1;32m    693[0m     use_cftime[38;5;241m=[39m[38;5;28mself[39m[38;5;241m.[39muse_cftime,
[1;32m    694[0m )

File [0;32m~/Abaconda3/anaconda3/envs/geo_env/lib/python3.10/site-packages/xarray/coding/times.py:176[0m, in [0;36m_decode_cf_datetime_dtype[0;34m(data, units, calendar, use_cftime)[0m
[1;32m    174[0m values [38;5;241m=[39m indexing[38;5;241m.[39mImplicitToExplicitIndexingAdapter(indexing[38;5;241m.[39mas_indexable(data))
[1;32m    175[0m example_value [38;5;241m=[39m np[38;5;241m.[39mconcatenate(
[0;32m--> 176[0m     [[43mfirst_n_items[49m[43m([49m[43mvalues[49m[43m,[49m[43m [49m[38;5;241;43m1[39;49m[43m)[49m [38;5;129;01mor[39;00m [[38;5;241m0[39m], last_item(values) [38;5;129;01mor[39;00m [[38;5;241m0[39m]]
[1;32m    177[0m )
[1;32m    179[0m [38;5;28;01mtry[39;00m:

File [0;32m~/Abaconda3/anaconda3/envs/geo_env/lib/python3.10/site-packages/xarray/core/formatting.py:77[0m, in [0;36mfirst_n_items[0;34m(array, n_desired)[0m
[1;32m     76[0m     array [38;5;241m=[39m array[indexer]
[0;32m---> 77[0m [38;5;28;01mreturn[39;00m [43mnp[49m[38;5;241;43m.[39;49m[43masarray[49m[43m([49m[43marray[49m[43m)[49m[38;5;241m.[39mflat[:n_desired]

File [0;32m~/Abaconda3/anaconda3/envs/geo_env/lib/python3.10/site-packages/xarray/core/indexing.py:459[0m, in [0;36mImplicitToExplicitIndexingAdapter.__array__[0;34m(self, dtype)[0m
[1;32m    458[0m [38;5;28;01mdef[39;00m [38;5;21m__array__[39m([38;5;28mself[39m, dtype[38;5;241m=[39m[38;5;28;01mNone[39;00m):
[0;32m--> 459[0m     [38;5;28;01mreturn[39;00m [43mnp[49m[38;5;241;43m.[39;49m[43masarray[49m[43m([49m[38;5;28;43mself[39;49m[38;5;241;43m.[39;49m[43marray[49m[43m,[49m[43m [49m[43mdtype[49m[38;5;241;43m=[39;49m[43mdtype[49m[43m)[49m

File [0;32m~/Abaconda3/anaconda3/envs/geo_env/lib/python3.10/site-packages/xarray/core/indexing.py:524[0m, in [0;36mLazilyIndexedArray.__array__[0;34m(self, dtype)[0m
[1;32m    523[0m array [38;5;241m=[39m as_indexable([38;5;28mself[39m[38;5;241m.[39marray)
[0;32m--> 524[0m [38;5;28;01mreturn[39;00m np[38;5;241m.[39masarray([43marray[49m[43m[[49m[38;5;28;43mself[39;49m[38;5;241;43m.[39;49m[43mkey[49m[43m][49m, dtype[38;5;241m=[39m[38;5;28;01mNone[39;00m)

File [0;32m~/Abaconda3/anaconda3/envs/geo_env/lib/python3.10/site-packages/xarray/backends/pydap_.py:42[0m, in [0;36mPydapArrayWrapper.__getitem__[0;34m(self, key)[0m
[1;32m     41[0m [38;5;28;01mdef[39;00m [38;5;21m__getitem__[39m([38;5;28mself[39m, key):
[0;32m---> 42[0m     [38;5;28;01mreturn[39;00m [43mindexing[49m[38;5;241;43m.[39;49m[43mexplicit_indexing_adapter[49m[43m([49m
[1;32m     43[0m [43m        [49m[43mkey[49m[43m,[49m[43m [49m[38;5;28;43mself[39;49m[38;5;241;43m.[39;49m[43mshape[49m[43m,[49m[43m [49m[43mindexing[49m[38;5;241;43m.[39;49m[43mIndexingSupport[49m[38;5;241;43m.[39;49m[43mBASIC[49m[43m,[49m[43m [49m[38;5;28;43mself[39;49m[38;5;241;43m.[39;49m[43m_getitem[49m
[1;32m     44[0m [43m    [49m[43m)[49m

File [0;32m~/Abaconda3/anaconda3/envs/geo_env/lib/python3.10/site-packages/xarray/core/indexing.py:815[0m, in [0;36mexplicit_indexing_adapter[0;34m(key, shape, indexing_support, raw_indexing_method)[0m
[1;32m    814[0m raw_key, numpy_indices [38;5;241m=[39m decompose_indexer(key, shape, indexing_support)
[0;32m--> 815[0m result [38;5;241m=[39m [43mraw_indexing_method[49m[43m([49m[43mraw_key[49m[38;5;241;43m.[39;49m[43mtuple[49m[43m)[49m
[1;32m    816[0m [38;5;28;01mif[39;00m numpy_indices[38;5;241m.[39mtuple:
[1;32m    817[0m     [38;5;66;03m# index the loaded np.ndarray[39;00m

File [0;32m~/Abaconda3/anaconda3/envs/geo_env/lib/python3.10/site-packages/xarray/backends/pydap_.py:50[0m, in [0;36mPydapArrayWrapper._getitem[0;34m(self, key)[0m
[1;32m     49[0m array [38;5;241m=[39m [38;5;28mgetattr[39m([38;5;28mself[39m[38;5;241m.[39marray, [38;5;124m"[39m[38;5;124marray[39m[38;5;124m"[39m, [38;5;28mself[39m[38;5;241m.[39marray)
[0;32m---> 50[0m result [38;5;241m=[39m [43mrobust_getitem[49m[43m([49m[43marray[49m[43m,[49m[43m [49m[43mkey[49m[43m,[49m[43m [49m[43mcatch[49m[38;5;241;43m=[39;49m[38;5;167;43;01mValueError[39;49;00m[43m)[49m
[1;32m     51[0m [38;5;66;03m# in some cases, pydap doesn't squeeze axes automatically like numpy[39;00m

File [0;32m~/Abaconda3/anaconda3/envs/geo_env/lib/python3.10/site-packages/xarray/backends/common.py:69[0m, in [0;36mrobust_getitem[0;34m(array, key, catch, max_retries, initial_delay)[0m
[1;32m     68[0m [38;5;28;01mtry[39;00m:
[0;32m---> 69[0m     [38;5;28;01mreturn[39;00m [43marray[49m[43m[[49m[43mkey[49m[43m][49m
[1;32m     70[0m [38;5;28;01mexcept[39;00m catch:

File [0;32m~/Abaconda3/anaconda3/envs/geo_env/lib/python3.10/site-packages/pydap/model.py:323[0m, in [0;36mBaseType.__getitem__[0;34m(self, index)[0m
[1;32m    322[0m out [38;5;241m=[39m copy[38;5;241m.[39mcopy([38;5;28mself[39m)
[0;32m--> 323[0m out[38;5;241m.[39mdata [38;5;241m=[39m [38;5;28;43mself[39;49m[38;5;241;43m.[39;49m[43m_get_data_index[49m[43m([49m[43mindex[49m[43m)[49m
[1;32m    324[0m [38;5;28;01mreturn[39;00m out

File [0;32m~/Abaconda3/anaconda3/envs/geo_env/lib/python3.10/site-packages/pydap/model.py:353[0m, in [0;36mBaseType._get_data_index[0;34m(self, index)[0m
[1;32m    352[0m [38;5;28;01melse[39;00m:
[0;32m--> 353[0m     [38;5;28;01mreturn[39;00m [38;5;28;43mself[39;49m[38;5;241;43m.[39;49m[43m_data[49m[43m[[49m[43mindex[49m[43m][49m

File [0;32m~/Abaconda3/anaconda3/envs/geo_env/lib/python3.10/site-packages/pydap/handlers/dap.py:170[0m, in [0;36mBaseProxy.__getitem__[0;34m(self, index)[0m
[1;32m    168[0m r [38;5;241m=[39m GET(url, [38;5;28mself[39m[38;5;241m.[39mapplication, [38;5;28mself[39m[38;5;241m.[39msession, timeout[38;5;241m=[39m[38;5;28mself[39m[38;5;241m.[39mtimeout,
[1;32m    169[0m         verify[38;5;241m=[39m[38;5;28mself[39m[38;5;241m.[39mverify)
[0;32m--> 170[0m [43mraise_for_status[49m[43m([49m[43mr[49m[43m)[49m
[1;32m    171[0m dds, data [38;5;241m=[39m safe_dds_and_data(r, [38;5;28mself[39m[38;5;241m.[39muser_charset)

File [0;32m~/Abaconda3/anaconda3/envs/geo_env/lib/python3.10/site-packages/pydap/net.py:52[0m, in [0;36mraise_for_status[0;34m(response)[0m
[1;32m     51[0m     text [38;5;241m=[39m [38;5;124m'[39m[38;5;124m'[39m
[0;32m---> 52[0m [38;5;28;01mraise[39;00m HTTPError(
[1;32m     53[0m     detail[38;5;241m=[39m(response[38;5;241m.[39mstatus [38;5;241m+[39m [38;5;124m'[39m[38;5;130;01m\n[39;00m[38;5;124m'[39m [38;5;241m+[39m text [38;5;241m+[39m [38;5;124m'[39m[38;5;130;01m\n[39;00m[38;5;124m'[39m [38;5;241m+[39m
[1;32m     54[0m             [38;5;124m'[39m[38;5;124mThis is redirect error. These should not usually raise [39m[38;5;124m'[39m [38;5;241m+[39m
[1;32m     55[0m             [38;5;124m'[39m[38;5;124man error in pydap beacuse redirects are handled [39m[38;5;124m'[39m [38;5;241m+[39m
[1;32m     56[0m             [38;5;124m'[39m[38;5;124mimplicitly. If it failed it is likely due to a [39m[38;5;124m'[39m [38;5;241m+[39m
[1;32m     57[0m             [38;5;124m'[39m[38;5;124mcircular redirect.[39m[38;5;124m'[39m),
[1;32m     58[0m     headers[38;5;241m=[39mresponse[38;5;241m.[39mheaders,
[1;32m     59[0m     comment[38;5;241m=[39mresponse[38;5;241m.[39mbody)

[0;31mHTTPError[0m: 302 Found
<!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
<html><head>
<title>302 Found</title>
</head><body>
<h1>Found</h1>
<p>The document has moved <a href="https://urs.earthdata.nasa.gov/oauth/authorize/?scope=uid&amp;app_type=401&amp;client_id=e2WVk8Pw6weeLUKZYOxvTQ&amp;response_type=code&amp;redirect_uri=https%3A%2F%2Fgpm1.gesdisc.eosdis.nasa.gov%2Fdata-redirect&amp;state=aHR0cHM6Ly9ncG0xLmdlc2Rpc2MuZW9zZGlzLm5hc2EuZ292L29wZW5kYXAvR1BNX0wzL0dQTV8zSU1FUkdERS4wNi8yMDAwLzA2LzNCLURBWS1FLk1TLk1SRy4zSU1FUkcuMjAwMDA2MDEtUzAwMDAwMC1FMjM1OTU5LlYwNi5uYzQuZG9kcz90aW1lX2JuZHMlNUIwOjE6MCU1RCU1QjA6MTowJTVE">here</a>.</p>
</body></html>

This is redirect error. These should not usually raise an error in pydap beacuse redirects are handled implicitly. If it failed it is likely due to a circular redirect.

During handling of the above exception, another exception occurred:

[0;31mHTTPError[0m                                 Traceback (most recent call last)
Cell [0;32mIn [4], line 8[0m
[1;32m      5[0m session[38;5;241m.[39mauth [38;5;241m=[39m ([38;5;124m'[39m[38;5;124mfaridfarhat[39m[38;5;124m'[39m, [38;5;124m'[39m[38;5;124mStand@2020@2020@[39m[38;5;124m'[39m)
[1;32m      7[0m store [38;5;241m=[39m xr[38;5;241m.[39mbackends[38;5;241m.[39mPydapDataStore[38;5;241m.[39mopen(url, session[38;5;241m=[39msession)
[0;32m----> 8[0m ds [38;5;241m=[39m [43mxr[49m[38;5;241;43m.[39;49m[43mopen_dataset[49m[43m([49m[43mstore[49m[43m)[49m

File [0;32m~/Abaconda3/anaconda3/envs/geo_env/lib/python3.10/site-packages/xarray/backends/api.py:539[0m, in [0;36mopen_dataset[0;34m(filename_or_obj, engine, chunks, cache, decode_cf, mask_and_scale, decode_times, decode_timedelta, use_cftime, concat_characters, decode_coords, drop_variables, inline_array, backend_kwargs, **kwargs)[0m
[1;32m    527[0m decoders [38;5;241m=[39m _resolve_decoders_kwargs(
[1;32m    528[0m     decode_cf,
[1;32m    529[0m     open_backend_dataset_parameters[38;5;241m=[39mbackend[38;5;241m.[39mopen_dataset_parameters,
[0;32m   (...)[0m
[1;32m    535[0m     decode_coords[38;5;241m=[39mdecode_coords,
[1;32m    536[0m )
[1;32m    538[0m overwrite_encoded_chunks [38;5;241m=[39m kwargs[38;5;241m.[39mpop([38;5;124m"[39m[38;5;124moverwrite_encoded_chunks[39m[38;5;124m"[39m, [38;5;28;01mNone[39;00m)
[0;32m--> 539[0m backend_ds [38;5;241m=[39m [43mbackend[49m[38;5;241;43m.[39;49m[43mopen_dataset[49m[43m([49m
[1;32m    540[0m [43m    [49m[43mfilename_or_obj[49m[43m,[49m
[1;32m    541[0m [43m    [49m[43mdrop_variables[49m[38;5;241;43m=[39;49m[43mdrop_variables[49m[43m,[49m
[1;32m    542[0m [43m    [49m[38;5;241;43m*[39;49m[38;5;241;43m*[39;49m[43mdecoders[49m[43m,[49m
[1;32m    543[0m [43m    [49m[38;5;241;43m*[39;49m[38;5;241;43m*[39;49m[43mkwargs[49m[43m,[49m
[1;32m    544[0m [43m[49m[43m)[49m
[1;32m    545[0m ds [38;5;241m=[39m _dataset_from_backend_dataset(
[1;32m    546[0m     backend_ds,
[1;32m    547[0m     filename_or_obj,
[0;32m   (...)[0m
[1;32m    555[0m     [38;5;241m*[39m[38;5;241m*[39mkwargs,
[1;32m    556[0m )
[1;32m    557[0m [38;5;28;01mreturn[39;00m ds

File [0;32m~/Abaconda3/anaconda3/envs/geo_env/lib/python3.10/site-packages/xarray/backends/store.py:29[0m, in [0;36mStoreBackendEntrypoint.open_dataset[0;34m(self, store, mask_and_scale, decode_times, concat_characters, decode_coords, drop_variables, use_cftime, decode_timedelta)[0m
[1;32m     26[0m [38;5;28mvars[39m, attrs [38;5;241m=[39m store[38;5;241m.[39mload()
[1;32m     27[0m encoding [38;5;241m=[39m store[38;5;241m.[39mget_encoding()
[0;32m---> 29[0m [38;5;28mvars[39m, attrs, coord_names [38;5;241m=[39m [43mconventions[49m[38;5;241;43m.[39;49m[43mdecode_cf_variables[49m[43m([49m
[1;32m     30[0m [43m    [49m[38;5;28;43mvars[39;49m[43m,[49m
[1;32m     31[0m [43m    [49m[43mattrs[49m[43m,[49m
[1;32m     32[0m [43m    [49m[43mmask_and_scale[49m[38;5;241;43m=[39;49m[43mmask_and_scale[49m[43m,[49m
[1;32m     33[0m [43m    [49m[43mdecode_times[49m[38;5;241;43m=[39;49m[43mdecode_times[49m[43m,[49m
[1;32m     34[0m [43m    [49m[43mconcat_characters[49m[38;5;241;43m=[39;49m[43mconcat_characters[49m[43m,[49m
[1;32m     35[0m [43m    [49m[43mdecode_coords[49m[38;5;241;43m=[39;49m[43mdecode_coords[49m[43m,[49m
[1;32m     36[0m [43m    [49m[43mdrop_variables[49m[38;5;241;43m=[39;49m[43mdrop_variables[49m[43m,[49m
[1;32m     37[0m [43m    [49m[43muse_cftime[49m[38;5;241;43m=[39;49m[43muse_cftime[49m[43m,[49m
[1;32m     38[0m [43m    [49m[43mdecode_timedelta[49m[38;5;241;43m=[39;49m[43mdecode_timedelta[49m[43m,[49m
[1;32m     39[0m [43m[49m[43m)[49m
[1;32m     41[0m ds [38;5;241m=[39m Dataset([38;5;28mvars[39m, attrs[38;5;241m=[39mattrs)
[1;32m     42[0m ds [38;5;241m=[39m ds[38;5;241m.[39mset_coords(coord_names[38;5;241m.[39mintersection([38;5;28mvars[39m))

File [0;32m~/Abaconda3/anaconda3/envs/geo_env/lib/python3.10/site-packages/xarray/conventions.py:534[0m, in [0;36mdecode_cf_variables[0;34m(variables, attributes, concat_characters, mask_and_scale, decode_times, decode_coords, drop_variables, use_cftime, decode_timedelta)[0m
[1;32m    523[0m     new_vars[k] [38;5;241m=[39m decode_cf_variable(
[1;32m    524[0m         k,
[1;32m    525[0m         v,
[0;32m   (...)[0m
[1;32m    531[0m         decode_timedelta[38;5;241m=[39mdecode_timedelta,
[1;32m    532[0m     )
[1;32m    533[0m [38;5;28;01mexcept[39;00m [38;5;167;01mException[39;00m [38;5;28;01mas[39;00m e:
[0;32m--> 534[0m     [38;5;28;01mraise[39;00m [38;5;28mtype[39m(e)([38;5;124mf[39m[38;5;124m"[39m[38;5;124mFailed to decode variable [39m[38;5;132;01m{[39;00mk[38;5;132;01m!r}[39;00m[38;5;124m: [39m[38;5;132;01m{[39;00me[38;5;132;01m}[39;00m[38;5;124m"[39m)
[1;32m    535[0m [38;5;28;01mif[39;00m decode_coords [38;5;129;01min[39;00m [[38;5;28;01mTrue[39;00m, [38;5;124m"[39m[38;5;124mcoordinates[39m[38;5;124m"[39m, [38;5;124m"[39m[38;5;124mall[39m[38;5;124m"[39m]:
[1;32m    536[0m     var_attrs [38;5;241m=[39m new_vars[k][38;5;241m.[39mattrs

[0;31mHTTPError[0m: Failed to decode variable 'time_bnds': 302 Found
<!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
<html><head>
<title>302 Found</title>
</head><body>
<h1>Found</h1>
<p>The document has moved <a href="https://urs.earthdata.nasa.gov/oauth/authorize/?scope=uid&amp;app_type=401&amp;client_id=e2WVk8Pw6weeLUKZYOxvTQ&amp;response_type=code&amp;redirect_uri=https%3A%2F%2Fgpm1.gesdisc.eosdis.nasa.gov%2Fdata-redirect&amp;state=aHR0cHM6Ly9ncG0xLmdlc2Rpc2MuZW9zZGlzLm5hc2EuZ292L29wZW5kYXAvR1BNX0wzL0dQTV8zSU1FUkdERS4wNi8yMDAwLzA2LzNCLURBWS1FLk1TLk1SRy4zSU1FUkcuMjAwMDA2MDEtUzAwMDAwMC1FMjM1OTU5LlYwNi5uYzQuZG9kcz90aW1lX2JuZHMlNUIwOjE6MCU1RCU1QjA6MTowJTVE">here</a>.</p>
</body></html>

This is redirect error. These should not usually raise an error in pydap beacuse redirects are handled implicitly. If it failed it is likely due to a circular redirect.
HTTPError: Failed to decode variable 'time_bnds': 302 Found
<!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
<html><head>
<title>302 Found</title>
</head><body>
<h1>Found</h1>
<p>The document has moved <a href="https://urs.earthdata.nasa.gov/oauth/authorize/?scope=uid&amp;app_type=401&amp;client_id=e2WVk8Pw6weeLUKZYOxvTQ&amp;response_type=code&amp;redirect_uri=https%3A%2F%2Fgpm1.gesdisc.eosdis.nasa.gov%2Fdata-redirect&amp;state=aHR0cHM6Ly9ncG0xLmdlc2Rpc2MuZW9zZGlzLm5hc2EuZ292L29wZW5kYXAvR1BNX0wzL0dQTV8zSU1FUkdERS4wNi8yMDAwLzA2LzNCLURBWS1FLk1TLk1SRy4zSU1FUkcuMjAwMDA2MDEtUzAwMDAwMC1FMjM1OTU5LlYwNi5uYzQuZG9kcz90aW1lX2JuZHMlNUIwOjE6MCU1RCU1QjA6MTowJTVE">here</a>.</p>
</body></html>

This is redirect error. These should not usually raise an error in pydap beacuse redirects are handled implicitly. If it failed it is likely due to a circular redirect.

